name: shopping_app_ui
description: Shopping App UI

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  email_validator: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  simple_animations: ^4.0.2
  flutter_launcher_icons: ^0.9.2
  share: ^2.0.4
  country_picker: ^2.0.15
  month_picker_dialog: ^0.4.0
  url_launcher: ^6.1.2
  like_button: ^2.0.4
  flutter_svg: ^1.1.0
  package_info: ^2.0.0
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  curved_navigation_bar: ^1.0.3
  image_picker: ^0.8.0+4
  image_cropper: 2.0.3
  intl: ^0.17.0
  provider: ^6.0.3
  shared_preferences: ^2.0.6
  odoo_rpc: ^0.5.1
  get: ^4.6.5
  syncfusion_flutter_pdf: ^20.1.58-beta
  path_provider: ^2.0.10
  location: ^4.4.0
  flutter_spinkit: ^5.1.0
  after_layout: 1.1.1+1
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.7
  sliding_up_panel: ^2.0.0+1
  slide_to_act: ^2.0.1
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  geocoding: ^2.0.4
  lottie: ^1.3.0
  permission_handler: ^9.2.0
  connectivity_plus: ^2.3.5
  hive_flutter: ^1.1.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  freezed_annotation: ^2.0.3
  riverpod_infinite_scroll: ^1.0.6
  infinite_scroll_pagination: ^3.2.0
  datetime_picker_formfield: ^2.0.1
  syncfusion_flutter_signaturepad: ^20.2.43
  open_file: ^2.1.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  pin_code_fields: ^7.4.0
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon_light/
    - assets/icon_dark/
    - assets/product_images/
    - assets/maps_images/
    - assets/json/googlemapsapi/
    - assets/json/lottieJson/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
  #       - asset: fonts/Schyler-Italic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
